import 'package:flutter/material.dart';
import 'package:mascotas/exception/datasource_exception.dart';

Future<void> tryCatchFormException(Future<void> Function() changeState) async {
  try {
    return await changeState();
  } on DatasourceException catch (_) {
    rethrow;
  } catch (error) {
    debugPrint(error.toString());
    throw DatasourceException("Ocurri√≥ un error inesperado");
  }
}